# -*- coding: utf-8 -*-
"""FiscPart MadgraphEvents.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o14cwyhxuCom4QQIbhWV7Hyy-IlbnYXx
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from scipy.stats import norm 
events=pd.read_csv('https://cernbox.cern.ch/index.php/s/5n2wG7OD7a0wYXX/download')
events.head()
#para crear vectores
data = np.genfromtxt('https://cernbox.cern.ch/index.php/s/5n2wG7OD7a0wYXX/download', delimiter=", ", names = ["px", "py", "pz","E"])
#grafica 
#plt.plot(data['px']) #eje y valor que tiene px, eje x el número de eventos
#grafica el histograma
plt.hist(data['px'])
plt.show() #vemos todos los muones
#momento tranverso 
plt.hist(np.sqrt(data['px']*data['px']+data['py']*data['py']))
plt.show()
#momento total
plt.hist(np.sqrt(data['px']*data['px']+data['py']*data['py']+data['pz']*data['pz']))
plt.show()